import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
const secondaryFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  adjustFontFallback: false,
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const sfProM = localFont({
  src: "./fonts/SF-Pro-Display-Medium.woff",
  variable: "--font-sfprom",
  weight: "500",
});

const sfProB = localFont({
  src: "./fonts/SF-Pro-Display-Bold.woff",
  variable: "--font-sfprob",
  weight: "700",
});

export const metadata: Metadata = {
  title: "Sacred eyes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${secondaryFont.variable} ${geistSans.variable} ${geistMono.variable} ${sfProM.variable} ${sfProB.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
